// Type definitions for SQLite schema compatibility

export enum PostType {
  COLLABORATION_REQUEST = "COLLABORATION_REQUEST",
  HELP_REQUEST = "HELP_REQUEST",
  TESTING_REQUEST = "TESTING_REQUEST",
  ASSIGNMENT_COLLABORATION = "ASSIGNMENT_COLLABORATION",
  OPEN_SOURCE_CONTRIBUTION = "OPEN_SOURCE_CONTRIBUTION",
  STARTUP_IDEA = "STARTUP_IDEA",
  TECHNICAL_DISCUSSION = "TECHNICAL_DISCUSSION",
}

export enum ProjectStatus {
  IDEATION = "IDEATION",
  PLANNING = "PLANNING",
  IN_PROGRESS = "IN_PROGRESS",
  BETA = "BETA",
  COMPLETED = "COMPLETED",
}

export enum PostVisibility {
  PUBLIC = "PUBLIC",
  UNIVERSITY = "UNIVERSITY",
  PRIVATE = "PRIVATE",
}

export enum NotificationType {
  COMMENT = "COMMENT",
  LIKE = "LIKE",
  COLLABORATION_REQUEST = "COLLABORATION_REQUEST",
  COLLABORATION_ACCEPTED = "COLLABORATION_ACCEPTED",
  ROOM_MENTION = "ROOM_MENTION",
  PROJECT_UPDATE = "PROJECT_UPDATE",
  SKILL_ENDORSED = "SKILL_ENDORSED",
}

export enum CollaborationStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
}

export enum MessageType {
  TEXT = "TEXT",
  CODE = "CODE",
  ANNOUNCEMENT = "ANNOUNCEMENT",
  SYSTEM = "SYSTEM",
}

export enum MemberRole {
  OWNER = "OWNER",
  MODERATOR = "MODERATOR",
  MEMBER = "MEMBER",
}

export enum DiscussionType {
  PROJECT = "PROJECT",
}

export enum ProficiencyLevel {
  BEGINNER = "BEGINNER",
  INTERMEDIATE = "INTERMEDIATE",
  ADVANCED = "ADVANCED",
  EXPERT = "EXPERT",
}

export enum ReportTargetType {
  POST = "POST",
  COMMENT = "COMMENT",
  USER = "USER",
}

export enum ReportStatus {
  PENDING = "PENDING",
  REVIEWED = "REVIEWED",
  DISMISSED = "DISMISSED",
}
